replicaCount: 1

image:
  repository: ghcr.io/synentra/synentra
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7080

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

resources: {}

podAnnotations: {}
podSecurityContext: {}
containerSecurityContext:
  allowPrivilegeEscalation: false

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 2
  readiness:
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3
